### ISSUE TITLE
run code

### ISSUE THREAD

**Issue by xiaofeifeifeifeifei** [val-iisc/3d-lmnet#9]
hello, when I run the bash scripts/train_plm.sh, there exit a question:
Traceback (most recent call last):
  File "train_plm.py", line 168, in <module>
    z_mean, z_log_sigma_sq = image_encoder(img_inp, FLAGS)
  File "/home/user05/.conda/envs/tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 442, in __iter__
    "Tensor objects are only iterable when eager execution is "
TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.
could you tell me how to solve, thanks .

**Comment by yxyyz** [comment]
> hello, when I run the bash scripts/train_plm.sh, there exit a question:
> Traceback (most recent call last):
> File "train_plm.py", line 168, in
> z_mean, z_log_sigma_sq = image_encoder(img_inp, FLAGS)
> File "/home/user05/.conda/envs/tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 442, in **iter**
> "Tensor objects are only iterable when eager execution is "
> TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.
> could you tell me how to solve, thanks .

hello, did u find the solution

**Comment by xiaofeifeifeifeifei** [comment]
I meet the same problem ,i think there is a problem with the source code&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "val-iisc/3d-lmnet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 下午3:33
收件人:&nbsp;"val-iisc/3d-lmnet"<3d-lmnet@noreply.github.com&gt;;
抄送:&nbsp;"高辉"<1799305203@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [val-iisc/3d-lmnet] run code (#9)





  
hello, when I run the bash scripts/train_plm.sh, there exit a question:
 Traceback (most recent call last):
 File "train_plm.py", line 168, in
 z_mean, z_log_sigma_sq = image_encoder(img_inp, FLAGS)
 File "/home/user05/.conda/envs/tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 442, in iter
 "Tensor objects are only iterable when eager execution is "
 TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.
 could you tell me how to solve, thanks .
  
hello, did u find the solution
